source 'http://rubygems.org'

gem 'backrack', '~> 0.0.2'
gem 'sprockets', '~> 2.4.0'
gem 'rack', '~> 1.4.1'
gem 'sass', '~> 3.1.15'
gem 'coffee-script', '~> 2.2.0'
gem 'uglifier', '~> 1.2.4'
gem 'bundler', '~> 1.2.0'
gem 'rake'
gem 'yui-compressor', '~> 0.9.6'
gem 'eco', '~> 1.0.0'
gem 'eventmachine', '~> 1.0.0'
gem 'em-websocket'
gem 'filewatch'
